;; question variables
(define sq1 "I can easily meet people.")
(define sq2 "I feel at ease in social situations.")
(define sq3 "I prefer socializing on weekends.")
(define sq4 "My idea of a good time involves hanging out with friends.")
(define sq5 "I easily voice my feelings.")
(define sq6 "It is easy for me to open up to people.")
(define sq7 "I easily make friends.")
(define sq8 "I find people interesting.")
(define sq9 "I value social interaction.")
(define sq10 "feel good after talking to someone.")

(define lq1 "I like and understand math.")
(define lq2 "Puzzles stimulate me.")
(define lq3 "It is difficult for my emotions to be changed.")
(define lq4 "I usually fulfill my plans.")
(define lq5 "I value facts over feelings.")
(define lq6 "I am not impulsive.")
(define lq7 "I can easily control and understand my emotions.")
(define lq8 "Strategy games stimulate me.")
(define lq9 "I easily forsee the consequences of my current actions.")
(define lq10 "I prefer to plan my day.")